import 'package:flutter/material.dart';

class AppColors {
  static Color primaryBlueColor = const Color(0xff0086FF);
  static Color primaryRedColor = const Color(0xffED502E);
  static Color blueTextColor = const Color(0xff022EF4);
  static Color whiteColor = Colors.white;
  static Color blackColor = Colors.black;
  static Color bgColor = const Color(0xffF6F6F6);
  static Color textColor = const Color(0xff071527);
  static Color firstCardColor = const Color(0xffFFF1F4);
  static Color secondCardColor = const Color(0xffF2F8FF);
  static Color thirdCardColor = const Color(0xffFFF7F6);
  static Color fourthCardColor = const Color(0xffFFF7EC);
  static Color greenColor = const Color(0xff02C30B);
  static Color headerColor = const Color(0xffF1F1F1);
  static Color lightOrangeColor = const Color(0xffFFF4F2);
  static Color color638EFA = const Color(0xff638EFA);
  static Color color7F68FA = const Color(0xff7F68FA);
  static Color colorFFA550 = const Color(0xffFFA550);
  static Color colorEA6061 = const Color(0xffEA6061);
  static Color borderColor = const Color(0xffEFEFEF);
  static Color color999999 = const Color(0xff999999);
  static Color tableButtonBg = const Color(0xffD9DFFF);
  static Color firstActionColor = const Color(0xffE5E3FF);
  static Color secondActionColor = const Color(0xffFFE7E3);
  static Color thirdActionColor = const Color(0xffE3F5FF);
  static Color fourthActionColor = const Color(0xffFFF0E3);
  static Color fifthActionColor = const Color(0xffFAE3FF);
  static Color sixthActionColor = const Color(0xffE3EBFF);
  static Color seventhActionColor = const Color(0xffE8FFE3);
  static Color eighthActionColor = const Color(0xffFFE3E3);
  static Color redColor = const Color(0xffFF0000);
  static Color colorE6F3FF = const Color(0xffE6F3FF);
  static Color colorEDA32E = const Color(0xffEDA32E);
  static Color colorFFF9F0 = const Color(0xffFFF9F0);
  static Color lightButtonColor = const Color(0xffE8E8E8);
  static Color colorDE3E1C = const Color(0xffDE3E1C);
  static Color cardBgColor = const Color(0xffF8F8F8);
}
