class Strings {
  static Map<String, Map<String, String>> translationsKeys = {
    "en": {
      "no_internet": "No internet Connection",
      "grievance_admin": "Grievances Admin",
      "Dashboard": "Dashboard",
      "Sign_in_to_start_your_session": "Sign in to start your session",
      "Email": "Email",
      "Password": "Password",
      "Sign_In": "Sign In",
      "Not_addressed": "Not addressed : ",
      "Pending": "Pending : ",
      "Resolved": "Resolved : ",
      "Discarded": "Discarded : ",
      "grievence_list": "Grievence List",
      "Search": "Search",
      "Add_New_Grievances": "+ Add New Grievances",
      "Si": "Si",
      "Grievance_Details": "Grievance Details",
      "Description": "Description",
      "Status_Updates": "Status Updates",
      "Message_Updates": "Message Updates",
      "Action": "Action",
      "Gievance_Id": "Grievance Id: ",
      "Customer_name": "Customer Name: ",
      "Address": "Address: ",
      "Date_Created": "Date Created: ",
      "Department": "Department: ",
      "Remark": " Remark",
      "Requested_By": "Requested By: ",
      "View_Grievances_Updates": "View Grievances Updates",
      "Status": "Status: ",
      "Respond": "Respond",
      "Email_History": "Email History",
      "Transfer_Grievances": "Transfer Grievances",
      "Update_Status": "Update Status",
      "Status_History": "Status History",
      "Edit": "Edit",
      "View": "View",
      "Delete": "Delete",
      "Change_Email_Status": "Change Email Status",
      "Message": "Message",
      "Subject": "Subject",
      "Thank_You": "Thank You",
      "Enter_Here": "Enter Here",
      "Send_Message": "Send Message",
      "enter_proper_message": "Enter proper message",
      "enter_proper_subject": "Enter proper subject",
      "Enter_your_message": "Enter Your Message",
      "Message_sent_successfully": "Message sent successfully",
      "Date": "Date",
      "Assign_to": "Assign to",
      "Assign_On": "Assign On",
      "Assigned_Details": "Assigned Details",
      "View_Email_History": "View Email History",
      "From_Customer": "From Customer",
      "From_Internal_User": "From Internal User",
      "To_Internal_User": "To Internal User",
      "To_Customer": "To Customer",
      "From_Admin_to_You": "From Admin to You",
      "From_You_to_Admin": "From You to Admin",
      "Message_field": "Message",
      "Transfer_Grievance": "Transfer Grievance",
      "Current_Department": "Current Department: ",
      "Transfer_Grievance_To": "Transfer Grievance To: ",
      "This_action_cannot_be_undone": "This action cannot be undone.",
      "Customer": "Customer: ",
      "Transfer_Reason": "Transfer Reason: ",
      "Save": "Save",
      "Change_Grievance_Status": "Change Grievance Status",
      "Remarks": "Remarks: ",
      "Alert": "Alert",
      "Sort_Order": "Sort Order",
      "Filters": "Filters",
      "Enter_here": "Enter here",
      "Status_normal": "Status",
      "Search_google_address": "Search google location",
      "Location": "Location",
      "Reset_Filters": "Reset Filters",
      "Sort_By_Date": "Sort By Date",
      "Change_Status": "Change Status: ",
      "Request_Id": "Request Id:",
      "Customer_Name": "Customer Name:",
      "UPDATED_BY": "UPDATED BY: ",
      "UPDATED_ON": "UPDATED ON: ",
      "NOTIFICATION": "NOTIFICATION: ",
      "REMARKS": "REMARKS: ",
      "Edit_Grievance": "Edit Grievance",
      "Assign_Department": "Assign Department",
      "Name": "Name",
      "Resolution_Date": "Resolution Date",
      "Resolution_Time": "Resolution Time",
      "View_Download_Files": "View / Download Files",
      "delete_title": "Are you sure you want to delete ?",
      "log_out_title": "Are you sure you want to log out ?",
      "cancel": "cancel",
      "confirm": "confirm",
      "Reports": "Reports",
      "From": "From",
      "To": "To",
      "Total_Grievance": "Total Grievance",
      "Immediate_Action": "Immediate Action",
      "Medium_Term": "Medium Term",
      "Long_Term": "Long Term",
      "Transferred": "Transferred",
      "Not_Responded": "Not Responded",
      "Grievance": "Grievance",
      "Unassigned_Grievances": "Unassigned Grievances",
      "Resolved/Closed": "Resolved/Closed",
      "Transffered_Grievances": "Transffered Grievances",
      "No Data Found": "No Data Found"
    },
    "or": {
      "no_internet": "କ internet ଣସି ଇଣ୍ଟରନେଟ୍ ସଂଯୋଗ ନାହିଁ |",
      "grievance_admin": "ଅଭିଯୋଗ ଆଡମିନି",
      "Dashboard": "ଡ୍ୟାସବୋର୍ଡ |",
      "Sign_in_to_start_your_session":
          "ଆପଣଙ୍କର ଅଧିବେଶନ ଆରମ୍ଭ କରିବାକୁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ |",
      "Email": "ଇମେଲ୍ କରନ୍ତୁ |",
      "Password": "ପାସୱାର୍ଡ",
      "Sign_In": "ଚୁକ୍ତି କରିବା",
      "Not_addressed": "ଠିକଣା ନୁହେଁ: ",
      "Pending": "ବିଚାରାଧୀନ: ",
      "Resolved": "ସମାଧାନ: ",
      "Discarded": "ପରିତ୍ୟାଗ: ",
      "grievence_list": "ଦୁ ie ଖ ତାଲିକା |",
      "Search": "ସନ୍ଧାନ କର |",
      "Add_New_Grievances": "ନୂତନ ଅଭିଯୋଗ ଯୋଡନ୍ତୁ |",
      "Si": "ସି",
      "Grievance_Details": "ଅଭିଯୋଗ ବିବରଣୀ",
      "Description": "ବର୍ଣ୍ଣନା",
      "Status_Updates": "ସ୍ଥିତି ଅଦ୍ୟତନଗୁଡିକ |",
      "Message_Updates": "ବାର୍ତ୍ତା ଅଦ୍ୟତନଗୁଡ଼ିକ",
      "Action": "କାର୍ଯ୍ୟ",
      "Gievance_Id": "ଅଭିଯୋଗ ଆଇଡି: ",
      "Customer_name": "ଗ୍ରାହକଙ୍କ ନାମ: ",
      "Address": "ଠିକଣା: ",
      "Date_Created": "ସୃଷ୍ଟି ତାରିଖ: ",
      "Department": "ବିଭାଗ: ",
      "Remark": " ଧ୍ୟାନ ଦିଅନ୍ତୁ |",
      "Requested_By": "ଅନୁରୋଧ: ",
      "View_Grievances_Updates": "ଅଭିଯୋଗ ଅଦ୍ୟତନଗୁଡିକ ଦେଖନ୍ତୁ |",
      "Status": "ସ୍ଥିତି: ",
      "Respond": "ଉତ୍ତର ଦିଅ",
      "Email_History": "ଇମେଲ୍ ଇତିହାସ |",
      "Transfer_Grievances": "ଅଭିଯୋଗ ସ୍ଥାନାନ୍ତର କରନ୍ତୁ |",
      "Update_Status": "ସ୍ଥିତି ଅଦ୍ୟତନ କରନ୍ତୁ |",
      "Status_History": "ସ୍ଥିତି ଇତିହାସ",
      "Edit": "ସଂପାଦନା କରନ୍ତୁ |",
      "View": "ଦର୍ଶନ କରନ୍ତୁ |",
      "Delete": "ବିଲୋପ କରନ୍ତୁ |",
      "Change_Email_Status": "ଇମେଲ ସ୍ଥିତି ପରିବର୍ତ୍ତନ କରନ୍ତୁ |",
      "Message": "ବାର୍ତ୍ତା |",
      "Subject": "ବିଷୟ",
      "Thank_You": "ଧନ୍ୟବାଦ",
      "Enter_Here": "ଏଠାରେ ପ୍ରବେଶ କରନ୍ତୁ |",
      "Send_Message": "ବାର୍ତ୍ତା ପଠାନ୍ତୁ |",
      "enter_proper_message": "ଉପଯୁକ୍ତ ବାର୍ତ୍ତା ପ୍ରବେଶ କରନ୍ତୁ |",
      "enter_proper_subject": "ଉପଯୁକ୍ତ ବିଷୟ ପ୍ରବେଶ କରନ୍ତୁ |",
      "Enter_your_message": "ଆପଣଙ୍କର ବାର୍ତ୍ତା ପ୍ରବେଶ କରନ୍ତୁ |",
      "Message_sent_successfully": "ବାର୍ତ୍ତା ସଫଳତାର ସହିତ ପଠାଗଲା |",
      "Date": "ତାରିଖ",
      "Assign_to": "ନ୍ୟସ୍ତ କରନ୍ତୁ |",
      "Assign_On": "ନ୍ୟସ୍ତ କରନ୍ତୁ |",
      "Assigned_Details": "ନ୍ୟସ୍ତ ହୋଇଥିବା ବିବରଣୀଗୁଡିକ |",
      "View_Email_History": "ଇମେଲ ଇତିହାସ ଦେଖନ୍ତୁ |",
      "From_Customer": "ଗ୍ରାହକଙ୍କ ଠାରୁ",
      "From_Internal_User": "ଆଭ୍ୟନ୍ତରୀଣ ବ୍ୟବହାରକାରୀଙ୍କ ଠାରୁ |",
      "To_Internal_User": "ଆଭ୍ୟନ୍ତରୀଣ ବ୍ୟବହାରକାରୀଙ୍କୁ |",
      "To_Customer": "ଗ୍ରାହକଙ୍କୁ",
      "From_Admin_to_You": "ଆଡମିନି ଠାରୁ ତୁମ ପର୍ଯ୍ୟନ୍ତ |",
      "From_You_to_Admin": "ତୁମଠାରୁ ଆଡମିନି ପର୍ଯ୍ୟନ୍ତ |",
      "Message_field": "ବାର୍ତ୍ତା |",
      "Transfer_Grievance": "ଅଭିଯୋଗ ସ୍ଥାନାନ୍ତର କରନ୍ତୁ |",
      "Current_Department": "ସାମ୍ପ୍ରତିକ ବିଭାଗ: ",
      "Transfer_Grievance_To": "ଅଭିଯୋଗ ସ୍ଥାନାନ୍ତର କରନ୍ତୁ: ",
      "This_action_cannot_be_undone":
          "ଏହି କାର୍ଯ୍ୟକୁ ପୂର୍ବବତ୍ କରାଯାଇପାରିବ ନାହିଁ |",
      "Customer": "ଗ୍ରାହକ: ",
      "Transfer_Reason": "ସ୍ଥାନାନ୍ତର କାରଣ: ",
      "Save": "ସଞ୍ଚୟ କରନ୍ତୁ |",
      "Change_Grievance_Status": "ଅଭିଯୋଗ ସ୍ଥିତି ପରିବର୍ତ୍ତନ କରନ୍ତୁ |",
      "Remarks": "ଟିପ୍ପଣୀ: ",
      "Alert": "ସତର୍କତା",
      "Sort_Order": "ଅର୍ଡର ସର୍ଟ କରନ୍ତୁ |",
      "Filters": "ଫିଲ୍ଟର୍ |",
      "Enter_here": "ଏଠାରେ ପ୍ରବେଶ କରନ୍ତୁ |",
      "Status_normal": "ସ୍ଥିତି",
      "Search_google_address": "ଗୁଗୁଲ୍ ଅବସ୍ଥାନ ଖୋଜ |",
      "Location": "ଅବସ୍ଥାନ",
      "Reset_Filters": "ଫିଲ୍ଟରଗୁଡିକ ପୁନ Res ସେଟ୍ କରନ୍ତୁ |",
      "Sort_By_Date": "ତାରିଖ ଅନୁଯାୟୀ ସର୍ଟ କରନ୍ତୁ |",
      "Change_Status": "ସ୍ଥିତି ପରିବର୍ତ୍ତନ କରନ୍ତୁ: ",
      "Request_Id": "Id ଅନୁରୋଧ:",
      "Customer_Name": "ଗ୍ରାହକଙ୍କ ନାମ:",
      "UPDATED_BY": "ଅଦ୍ୟତନ: ",
      "UPDATED_ON": "ଅଦ୍ୟତନ: ",
      "NOTIFICATION": "ବିଜ୍ଞପ୍ତି: ",
      "REMARKS": "ସ୍ମୃତି: ",
      "Edit_Grievance": "ଅଭିଯୋଗ ସଂପାଦନ କରନ୍ତୁ |",
      "Assign_Department": "ବିଭାଗ ନ୍ୟସ୍ତ କରନ୍ତୁ |",
      "Name": "ନାମ",
      "Resolution_Date": "ରେଜୋଲୁସନ ତାରିଖ",
      "Resolution_Time": "ରେଜୋଲୁସନ ସମୟ",
      "View_Download_Files": "ଫାଇଲଗୁଡିକ ଦେଖନ୍ତୁ / ଡାଉନଲୋଡ୍ କରନ୍ତୁ |",
      "delete_title": "ଆପଣ ବିଲୋପ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?",
      "log_out_title": "ଆପଣ ନିଶ୍ଚିତ କି ଆପଣ ଲଗ୍ ଆଉଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି?",
      "cancel": "ବାତିଲ୍ କରନ୍ତୁ |",
      "confirm": "ନିଶ୍ଚିତ କର |",
      "Reports": "ରିପୋର୍ଟଗୁଡିକ",
      "From": "ଠାରୁ",
      "To": "କୁ",
      "Total_Grievance": "ମୋଟ ଅଭିଯୋଗ",
      "Immediate_Action": "ତୁରନ୍ତ କାର୍ଯ୍ୟ",
      "Medium_Term": "ମଧ୍ୟମ ଅବଧି",
      "Long_Term": "ଦୀର୍ଘ ସ୍ଥାୟୀ",
      "Transferred": "ସ୍ଥାନାନ୍ତରିତ |",
      "Not_Responded": "ପ୍ରତିକ୍ରିୟାଶୀଳ ନୁହେଁ |",
      "Grievance": "ଅଭିଯୋଗ",
      "Unassigned_Grievances": "ଅଣସଂରକ୍ଷିତ ଅଭିଯୋଗଗୁଡିକ |",
      "Resolved/Closed": "ସମାଧାନ / ବନ୍ଦ |",
      "Transffered_Grievances": "ସ୍ଥାନାନ୍ତରିତ ଅଭିଯୋଗଗୁଡିକ |",
      "No Data Found": "କ Data ଣସି ତଥ୍ୟ ମିଳିଲା ନାହିଁ |"
    }
  };
}
