class Strings {
  static Map<String, Map<String, String>> translationsKeys = {
    "en": {
      "no_internet": "No internet Connection",
      "grievance_admin": "Grievances Admin",
      "Dashboard": "Dashboard",
      "Sign_in_to_start_your_session": "Sign in to start your session",
      "Email": "Email",
      "Password": "Password",
      "Sign_In": "Sign In",
      "Not_addressed": "Not addressed : ",
      "Pending": "Pending : ",
      "Resolved": "Resolved : ",
      "Discarded": "Discarded : ",
      "grievence_list": "Grievence List",
      "Search": "Search",
      "Add_New_Grievances": "+ Add New Grievances",
      "Si": "Si",
      "Grievance_Details": "Grievance  Details",
      "Description": "Description",
      "Status_Updates": "Status Updates",
      "Message_Updates": "Message Updates",
      "Action": "Action",
      "Gievance_Id": "Grievance Id: ",
      "Customer_name": "Customer Name: ",
      "Address": "Address: ",
      "Date_Created": "Date Created: ",
      "Department": "Department: ",
      "Remark": " Remark",
      "Requested_By": "Requested By: ",
      "View_Grievances_Updates": "View Grievances Updates",
      "Status": "Status: ",
      "Respond": "Respond",
      "Email_History": "Email History",
      "Transfer_Grievances": "Transfer Grievances",
      "Update_Status": "Update Status",
      "Status_History": "Status History",
      "Edit": "Edit",
      "View": "View",
      "Delete": "Delete",
      "Change_Email_Status": "Change Email Status",
      "Message": "Message",
      "Subject": "Subject",
      "Thank_You": "Thank You",
      "Enter_Here": "Enter Here",
      "Send_Message": "Send Message",
      "enter_proper_message": "Enter proper message",
      "enter_proper_subject": "Enter proper subject",
      "Enter_your_message": "Enter Your Message",
      "Message_sent_successfully": "Message sent successfully",
      "Date": "Date",
      "Assign_to": "Assign to",
      "Assign_On": "Assign On",
      "Assigned_Details": "Assigned Details",
      "View_Email_History": "View Email History",
      "From_Customer": "From Customer",
      "From_Internal_User": "From Internal User",
      "To_Internal_User": "To Internal User",
      "To_Customer": "To Customer",
      "From_Admin_to_You": "From Admin to You",
      "From_You_to_Admin": "From You to Admin",
      "Message_field": "Message",
    },
    "or": {
      "no_internet": "କ internet ଣସି ଇଣ୍ଟରନେଟ୍ ସଂଯୋଗ ନାହିଁ |",
      "grievance_admin": "ଗ୍ରାଇଭାନ୍ସ ପୋର୍ଟାଲ୍ |",
      "Dashboard": "ଡ୍ୟାସବୋର୍ଡ |"
    }
  };
}
